######################################################################
# Automatically generated by qmake (3.0) sön aug 3 14:11:33 2014
######################################################################

QT += testlib core network widgets
CONFIG += testcase
TEMPLATE = app
TARGET = tests
INCLUDEPATH += . ../client ../server

# Input
HEADERS += TestClient.hpp TestServer.hpp
SOURCES += main.cpp TestClient.cpp TestServer.cpp
